services:

  api-gateway:
    build:
      context: ../Web/backend/api-gateway
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../Web/backend/api-gateway:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - user-service
      - job-service
      - application-service
      - recommend-service

  user-service:
    build:
      context: ../Web/backend/user-service
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../Web/backend/user-service:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  job-service:
    build:
      context: ../Web/backend/job-service
      dockerfile: dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ../Web/backend/job-service:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  application-service:
    build:
      context: ../Web/backend/application-service
      dockerfile: dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ../Web/backend/application-service:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  recommend-service:
    build:
      context: ../Web/backend/recommend-service
      dockerfile: dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ../Web/backend/recommend-service:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - TZ=Asia/Ho_Chi_Minh
